FROM node:20-alpine AS base

WORKDIR /app

COPY secure/package*.json ./

RUN npm install --omit=dev
COPY secure/src ./src
COPY secure/views ./views

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 3001

CMD ["node", "src/app.js"]